schedule_url = 'http://e-rozklad.dut.edu.ua/timeTable/group'
database_url = 'postgres://lizgufqy:_vY_gy3Fi9CDrrfzBJ3J0by1o6v4INUI@stampy.db.elephantsql.com:5432/lizgufqy'
token = '284363665:AAFTYLX_J3q16YyKGzY1PQ1on6Yj-KPmXSo'

faculty_list = ['Інформаційних технологій', 'Телекомунікацій', 'Інформаційної безпеки', 
				'Загальні підрозділи', 'Менеджменту та підприємництва', 'Заочне навчання']

def group_list(firstDay, lastDay):
	group_list_data = [
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':3,
		'TimeTableForm[group]':613},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':3,
		'TimeTableForm[group]':617},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':3,
		'TimeTableForm[group]':936},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':902},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':890},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':861},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':895},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':881},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':904},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':860},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':903},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':894},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':6,
		'TimeTableForm[group]':885},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':755},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':750},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':803},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':804},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':754},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':752},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':806},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':756},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':751},
		
		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':7,
		'TimeTableForm[group]':753},

		{'TimeTableForm[date1]': firstDay,
		'TimeTableForm[date2]': lastDay,
		'TimeTableForm[faculty]':5,
		'TimeTableForm[course]':3,
		'TimeTableForm[group]':918},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 96, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 306, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 309, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 508, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 509, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 510, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 511, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 512, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 519, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 521, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 528, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 554, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 558, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 594, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 599, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 600, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 601, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 602, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 603, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 604, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 609, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 610, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 612, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 618, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 619, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 620, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 628, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 629, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 634, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 635, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 643, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 644, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 673, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 674, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 4, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 675, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 692, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 695, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	
	# проблема {'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 697, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 698, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 699, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 701, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 702, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 703, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 704, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 705, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 709, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 710, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	
	# нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 711, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 712, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 713, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 715, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 716, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 717, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 718, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 719, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 722, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 723, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 726, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 728, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 729, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 776, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 777, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 782, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 788, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 790, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 791, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 794, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 795, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 796, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 801, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 802, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 813, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 815, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 817, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 3, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 818, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	### нет такой группы {'TimeTableForm[course]': 6, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 819, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 820, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 821, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 822, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 823, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 824, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 825, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 827, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 828, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 829, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 830, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 831, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 832, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 833, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 836, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 837, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 838, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 839, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 840, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 841, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 842, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 844, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 845, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 846, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 850, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 852, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 853, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 854, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 855, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 856, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 857, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 5, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 858, 'TimeTableForm[faculty]': 2, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 888, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 907, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 910, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	
	# проблема {'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 914, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	# проблема {'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 915, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 916, 'TimeTableForm[faculty]': 1, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 919, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 2, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 920, 'TimeTableForm[faculty]': 4, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 921, 'TimeTableForm[faculty]': 7, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 929, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	{'TimeTableForm[course]': 1, 'TimeTableForm[date2]': lastDay, 'TimeTableForm[group]': 930, 'TimeTableForm[faculty]': 3, 'TimeTableForm[date1]': firstDay},
	]

	return group_list_data